// <auto-generated />
using EldenAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EldenAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260222225440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("EldenAPI.SiteOfGrace", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IconId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubRegionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text6")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text7")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text8")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("posX")
                        .HasColumnType("REAL");

                    b.Property<float>("posY")
                        .HasColumnType("REAL");

                    b.Property<float>("posZ")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("SitesOfGrace");
                });
#pragma warning restore 612, 618
        }
    }
}
